sudo: false
language: node_js
node_js:
  - '7'
addons: 
  firefox: "43.0"
install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - tar -xjf /tmp/firefox-43.0.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - npm install
script: npm run build:prod
#after_script:
#  - cat coverage/**/lcov.info | codacy-coverage
